schema_version: 1
kind: sensor
name: orbbec_gemini335l
variants:
  default:
    vars: {}
    urdf: variants/default/component.urdf
    mjcf: variants/default/component.mjcf
    meshdir: variants/default/meshes
root_link: camera_link
mount_frames:
  base_mount:
    parent: camera_link
  depth_optical:
    parent: depth_optical
  rgb_optical:
    parent: rgb_optical
  right_ir_optical:
    parent: right_ir_optical
