"""Auto-derive solo single-component units (single arm / single hand).

A component whose ``meta.yaml`` sets ``emit_solo_unit: true`` stands alone as
a robot. For each such component (arms/hands only) and each variant, this
step emits a loadable single-articulation unit under
``assets/units/<token>_<side>/`` by synthesizing a minimal recipe — that one
component, frozen to world, no mounts — and running the normal composer.

The recipe.yaml is *generated* (header-marked, do not hand-edit); keeping it
on disk means the existing hash / drift / ``validate_workstation`` flow works
unchanged. Arm+hand and other multi-component units keep explicit recipes.

Usage:
    python -m linker_robot_assets.composer.derive_solo [--check-drift]

``--check-drift`` re-derives every solo unit in memory (recipe + artifacts)
and exits non-zero if any committed file differs — used by CI to catch a
component edit or a generator change that wasn't re-committed.

Naming: unit token = component name minus a ``linkerhand_`` prefix (arms are
unchanged); side = ``l``/``r`` from the ``left``/``right`` variant. So
``arms/ar5_08`` → ``ar5_08_l`` / ``ar5_08_r`` and ``hands/linkerhand_l6`` →
``l6_l`` / ``l6_r``.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path

from .. import asset_root
from .compose import check_drift, compose, resolve_paths, write_if_changed
from .schemas import ComponentMeta

# Map a variant name to its unit-name side suffix.
_SIDE = {"left": "l", "right": "r"}

# Which component kinds can stand alone, and the composer role each uses.
# The role becomes the joint-name prefix, so it must match the roles the
# existing solo recipes used (`arm` / `hand`) to keep composed names stable.
_KIND_DIRS = (("arms", "arm"), ("hands", "hand"))


@dataclass(frozen=True)
class SoloSpec:
    unit_name: str
    role: str
    component_rel: str  # e.g. "arms/ar5_08"
    variant: str  # e.g. "left"


def solo_specs(assets_root: Path) -> list[SoloSpec]:
    """Enumerate the solo units to emit from flagged components."""
    specs: list[SoloSpec] = []
    for kind_dir, role in _KIND_DIRS:
        base = assets_root / "components" / kind_dir
        if not base.is_dir():
            continue
        for cdir in sorted(base.iterdir()):
            meta_path = cdir / "meta.yaml"
            if not meta_path.is_file():
                continue
            meta = ComponentMeta.load(meta_path)
            if not meta.emit_solo_unit:
                continue
            token = meta.name.removeprefix("linkerhand_")
            component_rel = f"{kind_dir}/{cdir.name}"
            for vname in sorted(meta.variants):
                side = _SIDE.get(vname, vname)
                specs.append(
                    SoloSpec(
                        unit_name=f"{token}_{side}",
                        role=role,
                        component_rel=component_rel,
                        variant=vname,
                    )
                )
    return specs


def recipe_text(spec: SoloSpec) -> str:
    """Deterministic generated recipe.yaml for a solo unit."""
    return (
        "# GENERATED by linker_robot_assets.composer.derive_solo — do not edit "
        "by hand.\n"
        "# Re-run `python -m linker_robot_assets.composer.derive_solo` after "
        "changing the\n"
        "# source component or its emit_solo_unit flag.\n"
        "schema_version: 1\n"
        f"name: {spec.unit_name}\n"
        f'description: "Auto-derived solo {spec.role} unit '
        f'({spec.component_rel}, {spec.variant}), frozen to world."\n'
        "components:\n"
        f"  {spec.role}:\n"
        f"    component: {spec.component_rel}\n"
        f"    variant: {spec.variant}\n"
        f"freeze_base: {spec.role}\n"
    )


def _write_unit(units_root: Path, assets_root: Path, spec: SoloSpec) -> None:
    unit_dir = units_root / spec.unit_name
    unit_dir.mkdir(parents=True, exist_ok=True)
    write_if_changed(unit_dir / "recipe.yaml", recipe_text(spec))
    paths = resolve_paths(unit_dir, assets_root)
    result = compose(paths)
    write_if_changed(paths.out_urdf, result.urdf_text)
    write_if_changed(paths.out_manifest, result.manifest_yaml)
    if result.mjcf_text is not None:
        write_if_changed(paths.out_mjcf, result.mjcf_text)
    print(f"[derive-solo] {spec.unit_name}: written")


def _check_unit(units_root: Path, assets_root: Path, spec: SoloSpec) -> list[str]:
    unit_dir = units_root / spec.unit_name
    if not unit_dir.is_dir():
        return [f"missing solo unit dir: {unit_dir}"]
    errors: list[str] = []
    recipe_path = unit_dir / "recipe.yaml"
    expected = recipe_text(spec)
    if not recipe_path.is_file():
        errors.append(f"missing generated recipe: {recipe_path}")
        return errors
    if recipe_path.read_text() != expected:
        errors.append(
            f"drift: {recipe_path} differs from freshly derived recipe "
            f"(re-run derive_solo)"
        )
        return errors
    paths = resolve_paths(unit_dir, assets_root)
    result = compose(paths)
    errors.extend(check_drift(paths, result))
    return errors


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description="Derive solo single-component units into assets/units/.",
    )
    p.add_argument(
        "--assets-root",
        type=Path,
        default=None,
        help="override assets root (default: the bundled asset tree)",
    )
    p.add_argument(
        "--check-drift",
        action="store_true",
        help="do not write; exit non-zero if any solo unit differs from fresh",
    )
    args = p.parse_args(argv)

    assets_root = (args.assets_root or asset_root()).resolve()
    units_root = assets_root / "units"
    specs = solo_specs(assets_root)
    if not specs:
        print("[derive-solo] no components flagged emit_solo_unit", file=sys.stderr)
        return 0

    if args.check_drift:
        errors: list[str] = []
        for spec in specs:
            errors.extend(_check_unit(units_root, assets_root, spec))
        if errors:
            for msg in errors:
                print(f"drift: {msg}", file=sys.stderr)
            return 1
        print(f"[derive-solo] {len(specs)} solo unit(s): no drift")
        return 0

    for spec in specs:
        _write_unit(units_root, assets_root, spec)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
